### ISSUE TITLE
[1.15.2] Crash

### ISSUE THREAD

**Issue by CrossVas** [lehjr/ModularPowerArmor#18]
**Version info**
Java version: jre-8u261
Minecraft Forge version: 1.15.2-forge-31.2.36

**Describe the bug**
Crash on load with the latest version of Forge 1.15.2

**Mod list**
Including versions, provided by crash report if game crashed:
Mod List:  
	forge-1.15.2-31.2.36-universal.jar Forge
	MPA-Lib-1.15.2-2.0.2.jar MPA-Lib
	ModularPowerArmor-1.15.2-2.0.2.jar Modular Power Armor 

**Log files**
latest.log pastebin: https://paste.ubuntu.com/p/Rt3C8rVWbQ/

If I am missing something, please, let me know. 

Thanks.

**Comment by CrossVas** [comment]
I'm blind. This issue is already known. Still present in 1.15.2. Sorry for spamming.

**Comment by eyeonus** [comment]
java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
	at com.github.lehjr.mpalib.client.gui.geometry.GradientAndArcCalculator.getArcPoints(GradientAndArcCalculator.java:77) ~[?:2.0.2] {re:classloading}
	at com.github.lehjr.mpalib.client.gui.geometry.DrawableCircle.<init>(DrawableCircle.java:64) ~[?:2.0.2] {re:classloading}
	at com.github.lehjr.modularpowerarmor.client.renderer.entity.PlasmaBoltEntityRenderer.<init>(PlasmaBoltEntityRenderer.java:26) ~[?:2.0.2] {re:classloading}
