### ISSUE TITLE
[1.16.4] Typecast Error

### ISSUE THREAD

**Issue by LetterN** [lehjr/ModularPowerArmor#20]
# Version info
Java version: 1.8.0_282 / JRE9
Minecraft Forge version: 35.1.37

## Describe the bug
When joining a multiplayer server this exemption happens. If done on JRE9 it throws **no** error and just disconnects you.

## To Reproduce
1. Join a multiplayer server
2. Get disconencted/timed out

## Expected behavior
No errors while joining.

# Mod list
Including versions, provided by crash report if game crashed:
[modlist.txt](https://github.com/lehjr/ModularPowerArmor/files/5938196/modlist.txt)

Smallest sub-list that still produces issue, if any exclusion testing was done:

## Log files
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
```
*snip*
[02:43:51] [Netty Client IO #0/ERROR]: Exception caught during firing event: com.electronwill.nightconfig.core.SimpleCommentedConfig cannot be cast to com.electronwill.nightconfig.core.file.CommentedFileConfig
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2463/859701702@114f9b95
java.lang.ClassCastException: com.electronwill.nightconfig.core.SimpleCommentedConfig cannot be cast to com.electronwill.nightconfig.core.file.CommentedFileConfig
	at net.minecraftforge.fml.config.ModConfig.getFullPath(ModConfig.java:98)
	at com.github.lehjr.powersuits.basemod.ModularPowersuits.lambda$new$0(ModularPowersuits.java:126)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:152)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:152)
	at net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$receiveSyncedConfig$5(ConfigTracker.java:123)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.config.ConfigTracker.receiveSyncedConfig(ConfigTracker.java:121)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.handleConfigSync(FMLHandshakeHandler.java:270)
	at net.minecraftforge.fml.util.ThreeConsumer.lambda$bindArgs$0(ThreeConsumer.java:43)
	at net.minecraftforge.fml.network.FMLHandshakeHandler.lambda$biConsumerFor$1(FMLHandshakeHandler.java:143)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128)
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162)
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatchLoginPacket(NetworkInstance.java:105)
	at net.minecraftforge.fml.network.FMLLoginWrapper.lambda$wrapperReceived$5(FMLLoginWrapper.java:69)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraftforge.fml.network.FMLLoginWrapper.wrapperReceived(FMLLoginWrapper.java:68)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88)
	at net.minecraft.client.network.login.ClientLoginNetHandler.func_209521_a(ClientLoginNetHandler.java:147)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:34)
	at net.minecraft.network.login.server.SCustomPayloadLoginPacket.func_148833_a(SCustomPayloadLoginPacket.java:11)
	at net.minecraft.network.NetworkManager.func_197664_a(NetworkManager.java:148)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:138)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
*snip*
```

## Screenshot
![image](https://user-images.githubusercontent.com/24603524/107135441-b07b8400-6935-11eb-921e-52d62d93bfe5.png)

**Comment by eyeonus** [comment]
The error is in the mod https://github.com/TheElectronWill/night-config, not this one.

**Comment by LetterN** [comment]
is it really? but it looks like modular powersuits called this?
`	at com.github.lehjr.powersuits.basemod.ModularPowersuits.lambda$new$0(ModularPowersuits.java:126)`

**Comment by lehjr** [comment]
Actually, this is the wrong repo, but not that important. Seems this can be replicated on a LAN game. It is going to take some time to investigate.
